#ifndef BRK_VIRTIO_H
#define BRK_VIRTIO_H

#include <brk/types.h>

#define VIRTIO_MAGIC_VALUE_OFFSET 0x000
#define VIRTIO_VERSION_OFFSET 0x004
#define VIRTIO_DEVICE_ID_OFFSET 0x008
#define VIRTIO_VENDOR_ID_OFFSET 0x00c
#define VIRTIO_DEVICE_FEATURES_OFFSET 0x010
#define VIRTIO_DEVICE_FEATURES_SEL_OFFSET 0x014
#define VIRTIO_DRIVER_FEATURES_OFFSET 0x020
#define VIRTIO_DRIVER_FEATURES_SEL_OFFSET 0x024
#define VIRTIO_QUEUE_SEL_OFFSET 0x030
#define VIRTIO_QUEUE_SIZE_MAX_OFFSET 0x034
#define VIRTIO_QUEUE_SIZE_OFFSET 0x038
#define VIRTIO_QUEUE_READY_OFFSET 0x044
#define VIRTIO_QUEUE_NOTIFY_OFFSET 0x050
#define VIRTIO_INTERRUPT_STATUS_OFFSET 0x060
#define VIRTIO_INTERRUPT_ACK_OFFSET 0x064
#define VIRTIO_STATUS_OFFSET 0x070
#define VIRTIO_QUEUE_DESC_LOW_OFFSET 0x080
#define VIRTIO_QUEUE_DESC_HIGH_OFFSET 0x084
#define VIRTIO_QUEUE_DRIVER_LOW_OFFSET 0x090
#define VIRTIO_QUEUE_DRIVER_HIGH_OFFSET 0x094
#define VIRTIO_QUEUE_DEVICE_LOW_OFFSET 0x0a0
#define VIRTIO_QUEUE_DEVICE_HIGH_OFFSET 0x0a4
#define VIRTIO_SHM_SEL_OFFSET 0x0ac
#define VIRTIO_SHM_LEN_LOW_OFFSET 0x0b0
#define VIRTIO_SHM_LEN_HIGH_OFFSET 0x0b4
#define VIRTIO_SHM_BASE_LOW_OFFSET 0x0b8
#define VIRTIO_SHM_BASE_HIGH_OFFSET 0x0bc
#define VIRTIO_QUEUE_RESET_OFFSET 0x0c0
#define VIRTIO_CONFIG_GENERATION_OFFSET 0x0fc
#define VIRTIO_CONFIG_OFFSET 0x100

#define VIRTIO_STATUS_ACKNOWLEDGE 1
#define VIRTIO_STATUS_DRIVER 2
#define VIRTIO_STATUS_DRIVER_OK 4
#define VIRTIO_STATUS_FEATURES_OK 8
#define VIRTIO_STATUS_NEEDS_RESET 64
#define VIRTIO_STATUS_FAILED 128

#define VIRTIO_F_INDIRECT_DESC 28
#define VIRTIO_F_EVENT_IDX 29
#define VIRTIO_F_VERSION_1 32
#define VIRTIO_F_ACCESS_PLATFORM 33
#define VIRTIO_F_RING_PACKED 34
#define VIRTIO_F_IN_ORDER 35
#define VIRTIO_F_ORDER_PLATFORM 36
#define VIRTIO_F_SR_IOV 37
#define VIRTIO_F_NOTIFICATION_DATA 38
#define VIRTIO_F_NOTIF_CONFIG_DATA 39
#define VIRTIO_F_RING_RESET 40
#define VIRTIO_F_ADMIN_VQ 41
#define VIRTIO_F_NOTIFY_ON_EMPTY 24
#define VIRTIO_F_ANY_LAYOUT 27

#define VIRTIO_DEVICE_ID_NET 1
#define VIRTIO_DEVICE_ID_BLK 2
#define VIRTIO_DEVICE_ID_CONSOLE 3
#define VIRTIO_DEVICE_ID_ENTROPY 4
#define VIRTIO_DEVICE_ID_MEMORY_BALLOON 5
#define VIRTIO_DEVICE_ID_SCSI_HOST 8
#define VIRTIO_DEVICE_ID_GPU 16
#define VIRTIO_DEVICE_ID_INPUT 18
#define VIRTIO_DEVICE_ID_CRYPTO 20
#define VIRTIO_DEVICE_ID_SOCKET 19
#define VIRTIO_DEVICE_ID_FILE_SYSTEM 26
#define VIRTIO_DEVICE_ID_RPMB 28
#define VIRTIO_DEVICE_ID_IOMMU 23
#define VIRTIO_DEVICE_ID_SOUND 25
#define VIRTIO_DEVICE_ID_MEMORY 24
#define VIRTIO_DEVICE_ID_I2C_ADAPTER 34
#define VIRTIO_DEVICE_ID_SCMI 32
#define VIRTIO_DEVICE_ID_GPIO 41
#define VIRTIO_DEVICE_ID_PMEM 27

#define VIRTIO_MAGIC_VALUE 0x74726976
#define VIRTIO_VENDOR_ID 0x554d4551

struct virtio_device {
	u64 phys_base;
	usize_t size;
	u32 irq;
	u32 id;
	u8 *mem_base;
	struct list_head list;
};

struct virtio_device *virtio_dev_create(u64 phys_base, usize_t size, u32 irq);
void virtio_dev_destroy(struct virtio_device *dev);
void virtio_dev_add(struct virtio_device *dev);
void virtio_dev_remove(struct virtio_device *dev);
struct virtio_device *virtio_dev_get(u32 id);

#endif
