obj-y += dtb.o
obj-y += ktime.o
obj-y += timekeeper.o
obj-y += init.o
obj-y += main.o
obj-y += panic.o
obj-y += printk.o
obj-y += cpu.o
obj-y += irq.o
obj-y += console.o
obj-y += refcnt.o
obj-y += signal.o

subdir-y += task
subdir-y += syscall
subdir-y += locking
