obj-y += init.o
obj-y += pipe.o
obj-y += dcache.o
obj-y += file.o
obj-y += inode.o
obj-y += mount.o
obj-y += super.o
obj-y += exec.o
obj-y += path.o
obj-y += filesystem.o
obj-y += namei.o
obj-y += fdtable.o
obj-y += fsinfo.o

subdir-y += tmpfs
subdir-y += procfs
subdir-y += brkfs
