src := $(build)
obj := $(KERNEL_BUILD_ROOT)/$(build)

obj-y :=
subdir-y :=

include $(src)/Makefile

obj-y := $(strip $(obj-y))
subdir-y := $(strip $(subdir-y))

obj-y-full := $(addprefix $(obj)/,$(obj-y))
subdir-built-in := $(addprefix $(obj)/,$(patsubst %,%/built-in.o,$(subdir-y)))

$(obj)/built-in.o: $(obj-y-full) $(subdir-built-in)
	@echo "  LD      $@"
	@$(LD) $(LDFLAGS) -r -o $@ $^

$(subdir-built-in): FORCE
	@$(MAKE) -f scripts/Makefile.build build=$(patsubst $(KERNEL_BUILD_ROOT)/%,%,$(@D))

$(obj)/%.o: $(src)/%.c
	@mkdir -p $(dir $@)
	@echo "  CC      $@"
	@$(CC) $(CFLAGS) -c -o $@ $<

$(obj)/%.o: $(src)/%.S
	@mkdir -p $(dir $@)
	@echo "  AS      $@"
	@$(CC) $(CFLAGS) -c -o $@ $<

.PHONY: FORCE

-include $(obj-y-full:.o=.d)
